#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]
then
  echo '================='
  echo '| Snyk Scanning |'
  echo '================='
  echo -e '\nUsage: snyk-scan run\n'
  exit 0
fi

if [[ "$APP" == "" ]]
then
  echo "No application found."
  exit 1
elif [[ "${TAG}" == "" ]]
then
  echo "No image tag found."
  exit 1
fi

if [[ "$PERMISSION" != "DEVOPS" ]]; then
  echo "Unauthorized: You don't have permission to run this command! Please contact DevOps Admin."
  exit 1
else

STATUS=$1
if [[ "${STATUS}" != "run" ]]
then
  echo "No argument specified or invalid option."
  echo "Type -h or --help for more details."
  exit 1
fi
shift

npm install -g snyk
docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
docker pull $CI_REGISTRY_IMAGE:$TAG
snyk auth $SNYK_TOKEN
snyk monitor --docker $CI_REGISTRY_IMAGE:$TAG --file=$PWD/Dockerfile --project-name=$CI_PROJECT_NAME/${!APP}/app-image --org=$SNYK_ORG_APP
snyk test --docker $CI_REGISTRY_IMAGE:$TAG || true

fi